import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { ChakraProvider } from '@chakra-ui/react';

// You can import a custom theme if you have one
// import theme from '../theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ChakraProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    // </ChakraProvider>
  );
}
